.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "M_TRIE_REMOVE" "3" "March 2017" "lovasko" "m_trie"
.
.SH "NAME"
\fBm_trie_remove\fR \- remove a key from the trie
.
.SH "LIBRARY"
m_trie (\-lmtrie)
.
.SH "SYNOPSIS"
\fB#include <m_trie\.h>\fR
.
.P
\fBint\fR
.
.br
\fIm_trie_remove\fR(\fBm_trie*\fR \fItrie\fR, \fBchar*\fR \fIkey\fR, \fBsize_t\fR \fIlen\fR)
.
.SH "DESCRIPTION"
The \fIm_trie_remove\fR function removes a specified \fIkey\fR from the \fItrie\fR\. This function merely tags the internal tree node as free and does not perform the actual deallocation of the memory due to performance reasons\. To trigger the deallocation process, use the \fIm_trie_trim\fR function\.
.
.SH "TIME COMPLEXITY"
\fBO\fR(\fIk\fR), where \fIk\fR is the \fIlen\fRgth of the \fIkey\fR\.
.
.SH "RETURN VALUES"
.
.TP
M_TRIE_OK
success
.
.TP
M_TRIE_E_NULL
\fItrie\fR and/or \fIkey\fR are \fBNULL\fR
.
.TP
M_TRIE_E_INVALID
\fIkey\fR contains invalid characters (as specified by the hashing function)
.
.TP
M_TRIE_E_LENGTH
\fIlen\fR is zero
.
.SH "SEE ALSO"
m_trie_remove_prefix(3), m_trie_trim(3)
