.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "M_TRIE_INSERT" "3" "March 2017" "lovasko" "m_trie"
.
.SH "NAME"
\fBm_trie_insert\fR \- insert a key/value pair into the trie
.
.SH "LIBRARY"
m_trie (\-lmtrie)
.
.SH "SYNOPSIS"
\fB#include <m_trie\.h>\fR
.
.P
\fBint\fR
.
.br
\fIm_trie_insert\fR(\fBm_trie*\fR \fItrie\fR, \fBchar*\fR \fIkey\fR, \fBsize_t\fR \fIlen\fR, \fBvoid*\fR \fIdata\fR)
.
.SH "DESCRIPTION"
The \fIm_trie_insert\fR function inserts a specified \fIkey\fR/\fIdata\fR pair into the \fItrie\fR\. It is allowed for the \fIdata\fR value to be \fBNULL\fR\.
.
.SH "TIME COMPLEXITY"
\fBO\fR(\fIk\fR), where \fIk\fR is the \fIlen\fRgth of the \fIkey\fR\.
.
.SH "RETURN VALUES"
.
.TP
M_TRIE_OK
success
.
.TP
M_TRIE_E_NULL
\fItrie\fR and/or \fIkey\fR are \fBNULL\fR
.
.TP
M_TRIE_E_INVALID
\fIkey\fR contains invalid characters (as specified by the hashing function)
.
.TP
M_TRIE_E_LENGTH
\fIlen\fR is zero
.
.SH "SEE ALSO"
m_trie_remove(3), m_trie_search(3)
